[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
#log_cli_format = "%(asctime)s [%(levelname)8s] (%(filename)s:%(lineno)s)"
log_cli_format = "%(asctime)s [%(levelname)8s](%(filename)s:%(lineno)s):%(message)s "
#log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli_date_format = "%H:%M:%S"